# Generated by Django 4.1.7 on 2023-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_stripe_customer_id_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
