# Generated by Django 4.1.7 on 2023-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_account_connected",
            field=models.BooleanField(default=False),
        ),
    ]
